### ISSUE TITLE
Translate other Algo Examples to codebase

### ISSUE THREAD

**Issue by obent1** [slremy/netsapi#11]
Currently random and Vanilla GA examples

**Comment by slremy** [comment]
Should this be included in this repo? If so that means that the pip install process (managed via setup.py) might need to be updated to minimize workspace pollution.

**Comment by obent1** [comment]
Good point - will link with other shared repo

**Comment by slremy** [comment]
I think there's a way to update the setup. I've proceeded to include an examples directory with the random search example.
